-- MySQL Script generated by MySQL Workbench
-- Wed Jul  8 02:50:44 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema javadesktop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema javadesktop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS javadesktop DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE javadesktop ;

-- -----------------------------------------------------
-- Table javadesktop.Cliente
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS javadesktop.Cliente (
  cpf VARCHAR(14) NOT NULL,
  nome VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL,
  telefone VARCHAR(15) NOT NULL,
  PRIMARY KEY (cpf))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table javadesktop.Produto
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS javadesktop.Produto (
  idProduto INT NOT NULL AUTO_INCREMENT,
  descricao VARCHAR(50) NOT NULL,
  quantidade INT NOT NULL,
  preco DOUBLE NOT NULL,
  PRIMARY KEY (idProduto))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table javadesktop.Funcao
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS javadesktop.Funcao (
  idFuncao INT NOT NULL AUTO_INCREMENT,
  nome VARCHAR(15) NOT NULL,
  salario DOUBLE NOT NULL,
  PRIMARY KEY (idFuncao))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table javadesktop.Funcionario
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS javadesktop.Funcionario (
  idFuncionario INT NOT NULL,
  cpf VARCHAR(14) NOT NULL,
  nome VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL,
  telefone VARCHAR(15) NOT NULL,
  login VARCHAR(15) NOT NULL,
  senha VARCHAR(64) NOT NULL,
  Funcao_idFuncao INT NOT NULL,
  PRIMARY KEY (idFuncionario),
  INDEX fk_Funcionario_Funcao1_idx (Funcao_idFuncao ASC) VISIBLE,
  CONSTRAINT fk_Funcionario_Funcao1
    FOREIGN KEY (Funcao_idFuncao)
    REFERENCES javadesktop.Funcao (idFuncao)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table javadesktop.endereco
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS javadesktop.endereco (
  logradouro VARCHAR(50) NOT NULL,
  numero INT NOT NULL,
  complemento VARCHAR(45) NOT NULL,
  bairro VARCHAR(45) NOT NULL,
  cidade VARCHAR(45) NOT NULL,
  uf VARCHAR(2) NOT NULL,
  cep VARCHAR(9) NULL,
  Cliente_cpf VARCHAR(14) NOT NULL,
  PRIMARY KEY (Cliente_cpf),
  CONSTRAINT fk_endereco_Cliente
    FOREIGN KEY (Cliente_cpf)
    REFERENCES javadesktop.Cliente (cpf)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table javadesktop.FormaDePagamento
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS javadesktop.FormaDePagamento (
  idFormaDePagamento INT NOT NULL AUTO_INCREMENT,
  descricao VARCHAR(15) NULL,
  PRIMARY KEY (idFormaDePagamento))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table javadesktop.PedidoDeCompra
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS javadesktop.PedidoDeCompra (
  idPedidoDeCompra INT NOT NULL AUTO_INCREMENT,
  data DATE NULL,
  hora TIME NULL,
  Cliente_cpf VARCHAR(14) NOT NULL,
  FormaDePagamento_idFormaDePagamento INT NOT NULL,
  Funcionario_idFuncionario INT NOT NULL,
  PRIMARY KEY (idPedidoDeCompra),
  INDEX fk_PedidoDeCompra_Cliente1_idx (Cliente_cpf ASC) VISIBLE,
  INDEX fk_PedidoDeCompra_FormaDePagamento1_idx (FormaDePagamento_idFormaDePagamento ASC) VISIBLE,
  INDEX fk_PedidoDeCompra_Funcionario1_idx (Funcionario_idFuncionario ASC) VISIBLE,
  CONSTRAINT fk_PedidoDeCompra_Cliente1
    FOREIGN KEY (Cliente_cpf)
    REFERENCES javadesktop.Cliente (cpf)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_PedidoDeCompra_FormaDePagamento1
    FOREIGN KEY (FormaDePagamento_idFormaDePagamento)
    REFERENCES javadesktop.FormaDePagamento (idFormaDePagamento)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_PedidoDeCompra_Funcionario1
    FOREIGN KEY (Funcionario_idFuncionario)
    REFERENCES javadesktop.Funcionario (idFuncionario)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table javadesktop.ItemPedidoDeCompra
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS javadesktop.ItemPedidoDeCompra (
  PedidoDeCompra_idPedidoDeCompra INT NOT NULL,
  quantidade INT NOT NULL,
  Produto_idProduto INT NOT NULL,
  PRIMARY KEY (PedidoDeCompra_idPedidoDeCompra),
  INDEX fk_ItemPedidoDeCompra_PedidoDeCompra1_idx (PedidoDeCompra_idPedidoDeCompra ASC) VISIBLE,
  INDEX fk_ItemPedidoDeCompra_Produto1_idx (Produto_idProduto ASC) VISIBLE,
  CONSTRAINT fk_ItemPedidoDeCompra_PedidoDeCompra1
    FOREIGN KEY (PedidoDeCompra_idPedidoDeCompra)
    REFERENCES javadesktop.PedidoDeCompra (idPedidoDeCompra)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_ItemPedidoDeCompra_Produto1
    FOREIGN KEY (Produto_idProduto)
    REFERENCES javadesktop.Produto (idProduto)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table javadesktop.Usuario
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS javadesktop.Usuario (
  idUsuario INT NOT NULL AUTO_INCREMENT,
  login VARCHAR(15) NOT NULL,
  senha VARCHAR(64) NOT NULL,
  PRIMARY KEY (idUsuario))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;